### ISSUE TITLE
helm部署开启认证

### ISSUE THREAD

**Issue by DanielLiangHH** [vesoft-inc/nebula-operator#116]
我helm启动需要开启认证，发现nebula-cluster里面nebula-cluster.yaml文件缺少以下配置
```yaml
spec:
  graphd:
    config: {{ toYaml .Values.nebula.graphd.config | nindent 6 }}
```
补充后在valus.yaml文件添加 enable_authorize 配置才得以开启认证
```yaml
nebula:
  graphd:
    config:
      "enable_authorize": "true"
      "auth_type": "password"
```
