### ISSUE TITLE
Deploy nebula operator with ArgoCD

### ISSUE THREAD

**Issue by robcinko** [vesoft-inc/nebula-operator#146]
Hi,

we want to deploy nebula operator with CD tool ArgoCD, but we have a problem with specify k8s namespace. In values.yaml file we cant define namespace. Do you have any suggestions how to solve this problem ?

Thank you

**Comment by wey-gu** [comment]
@MegaByte875 could you plz help advise on this?

**Comment by robcinko** [comment]
Maybe it can be solved by edit `{{ .Values.namespace | default .Release.Namespace }}` in _helpers.tpl file.

**Comment by wey-gu** [comment]
Did you try changing the metadata.namespace from its CRD as follow?

```yaml
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaCluster
metadata:
  name: nebula
  namespace: default # <-----------
spec:
  graphd:
```
