### ISSUE TITLE
typo in nebula-cluster.yaml file causing deployment failure

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula-operator#170]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
Upgrade nebula cluster to v3.3.0 using helm chart failed

Upgrade nebula cluster to v3.3.0 using helm chart failed with below error
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(NebulaCluster.spec.storaged): unknown field "dataVolumeClaims" in io.nebula-graph.apps.v1alpha1.NebulaCluster.spec.storaged
helm.go:84: [debug] error validating "": error validating data: ValidationError(NebulaCluster.spec.storaged): unknown field "dataVolumeClaims" in io.nebula-graph.apps.v1alpha1.NebulaCluster.spec.storaged
```

Looking at the code...these seems a typo in nebula-cluster.yaml files
```
    dataVolumeClaims:
    - resources:
        requests:
          storage: {{ .Values.nebula.storaged.dataStorage }}
      {{- if .Values.nebula.storageClassName }}
      storageClassName: {{ .Values.nebula.storageClassName }}
      {{- end }}
```

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**
