### ISSUE TITLE
br barkup in k8s always report error 

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#221]
with follow full brbackup config，report error
 ![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/e0bebfa9-5568-4f5f-9255-355c46850f9e)

br-config file:
```
containers:
        - image: reg.vesoft-inc.com/cloud-dev/br-ent:v3.5.1
          imagePullPolicy: Always
          name: backup
          command:
            - /bin/sh
            - -ecx
            - exec /usr/local/bin/br-ent backup full --meta 10.244.3.107:9559 --storage s3://test-qa
            - --s3.access_key 4ZExgdMpxdkIZZIj2sJO
            - --s3.secret_key 9s38kN6Tdy5sa1yjl4wtg6Mgro0toslEUyrThXo9
            - --s3.region us-west-2
            - --s3.endpoint https://minio.vesoft-inc.com/
```
when i set meta and storage to 1 line, as follows，then，another error reported：
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/82e509b9-14c5-4fe8-a472-497002bad1ab)
```
command:
            - /bin/sh
            - -ecx
            - exec /usr/local/bin/br-ent backup full --meta nebula-metad-0.nebula-metad-headless.nebula.svc.cluster.local:9559 --storage s3://test-qa
            - --s3.access_key minio
            - --s3.secret_key minio123
            - --s3.region us-west-2
            - --s3.endpoint http://192.168.8.202:32000/

```

kevin explain as the  line feed not be handled correctly

**Your Environments (__required__)**

  agent:
    image: reg.vesoft-inc.com/cloud-dev/nebula-agent
    version: v3.5.0 
    
    br:
    image: reg.vesoft-inc.com/cloud-dev/br-ent:v3.5.1

**Expected behavior**
not report error
