### ISSUE TITLE
k8s after open logrotate, nebula restart failed

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#226]
**Please check the FAQ documentation before raising an issue**
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/5a343cd4-5c85-46de-aea5-120867fb0fd9)

```  
Normal   Pulled     25s                kubelet            Successfully pulled image "reg.vesoft-inc.com/cloud-dev/nebula-agent:v3.5.1" in 983.697057ms (983.704709ms including waiting)
  Warning  BackOff    9s (x4 over 39s)   kubelet            Back-off restarting failed container ng-agent in pod nebula-metad-0_nebula(44ed5413-29ea-43b6-b4b0-68d621362689)
```
the conf：
```
graphd:
  config:
    "timestamp_in_logfile_name": "true"
metad:
  config:
    "timestamp_in_logfile_name": "true"
storaged:
  config:
    "timestamp_in_logfile_name": "true"
logRotate:
  rotate: 3 #轮询三次就删除；
  size: 3K #达到3k大小就参与轮询；
```

**Your Environments (__required__)**

nebulaOperator:
image: reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.2
nebula:
image: reg.vesoft-inc.com/rc/nebula-graphd-ent:v3.5.0-sc
agent:
image: reg.vesoft-inc.com/cloud-dev/nebula-agent:v3.5.1

**Expected behavior**
start success
