### ISSUE TITLE
[k8s] when enable_meta_ssl and execute br restore then report error 

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#233]
when execute br backup with enable_meta_ssl and cert. then restore it report error 
restore stuck to MetadComplete， without new cluster generated.
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/6a9220b3-1b98-4d52-acf9-173fe9eb8851)
the error displayed:
```
 message: 'storaged data playback failed: rpc error: code = Unknown desc = exit
 status 1' 
```
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/64e0c168-15fc-4fcb-a199-1fbf0740be2f)

restore file config:
```
# cat mtls_restore.yaml
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaRestore
metadata:
  name: restore1
  namespace: nebula-s
spec:
  br:
    clusterName: nebula-s
    backupName: "BACKUP_2023_08_02_10_26_14"
    concurrency: 5
    s3:
      region: "us-west-2"
      bucket: "test-qa"
      endpoint: "http://192.168.8.202:32000"
      secretName: "aws-s3-secret"
```

**Your Environments (__required__)**

nebula-ent-sc-rc包
镜像是：
image: reg.vesoft-inc.com/rc/nebula-storaged-ent
version: v3.5.0-sc
operator镜像是：
reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.4
br镜像是：
reg.vesoft-inc.com/cloud-dev/br-ent:v3.5.1

**Expected behavior**
execute success
