### ISSUE TITLE
show zones，hosts zone is incorrect

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#252]
当前有3个host，3个storage，3个graph，当node2磁盘空间不足，两个storage节点分布在node1，一个storage节点分布在master。
而show zones展示的，却是3个storage分布在3个zone上。

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/60338fb5-c3d5-4ebb-b727-900e2a7ddbc3)

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/49e704d3-8c89-448f-ad52-182ae211f91b)

当前上k8s上通过在三个node上打tag，来模拟三个不同的zone：
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/b87ce750-a417-4c6c-b624-ec2b078be838)

**Your Environments (__required__)**

operator：reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.8
nebula-ent: reg.vesoft-inc.com/rc/nebula-storaged-ent:v3.5.0-sc
需要设置operator的sa等权限
```
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
    - clusterroles
  verbs:
    - create
    - delete
    - get
    - list
    - update 
    - watch   //这个是需要多配置的
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
```

**How To Reproduce(__required__)**

其中一个node磁盘空间紧张时，创建集群nebula（1meta-3graph-3storage）

**Expected behavior**
display zone correctly
