### ISSUE TITLE
`describe na` generate two lines log with different size

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#313]
when auto scale，and `describe na`  generate two lines log with different size，actual has 7 graph pods，one log show 7 and the other show 4
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/2bb120df-4e35-404b-80ac-f2161671ffd9)

**Your Environments (__required__)**

nebula-operator: snap-1.18

**How To Reproduce(__required__)**

1. auto scale with follow file:
autoscale.yaml
```
apiVersion: autoscaling.nebula-graph.io/v1alpha1
kind: NebulaAutoscaler
metadata:
  name: nebula-autoscaler
  namespace: nebula
spec:
  nebulaClusterRef:
    name: nebulazcert
  graphdPolicy:
    minReplicas: 2
    maxReplicas: 10
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    behavior:
      scaleDown:
        selectPolicy: Disabled
  pollingPeriod: 30s
```
2. with many query
3. show na detail: `kubectl  -n nebula describe  na  nebula-autoscaler`

**Expected behavior**

generate one line log with size 7
