### ISSUE TITLE
restore cross namespace, when set clusterNamespace with wrong value ,no error log print

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#451]
as title:

restore cross namespace , when set `clusterNamespace` as `notexistns` , namespace `notexistns` not exists.
```
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaRestore
metadata:
  name: br-restore-minc
  #namespace: nebula
spec:
  config:
    backupName: BACKUP_2024_02_26_06_42_02
    clusterName: nebulamt
    clusterNamespace: notexistns
    concurrency: 50
    s3:
      region: "us-west-2"
      bucket: "nebula-br-test2"
      endpoint: "https://s3.us-west-2.amazonaws.com"
      secretName: "aws-secret-ql3"
```
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/4c7c302a-17f8-484e-93e7-b3553426d49a)

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/652d394d-0fd3-4fcc-b6a3-18132fe9f696)

**Your Environments (__required__)**

operator：reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.37
br-ent: reg.vesoft-inc.com/cloud-dev/br-ent:v3.7.0
agent: reg.vesoft-inc.com/cloud-dev/nebula-agent:snap
nebula: reg.vesoft-inc.com/qa/nebula-graphd-ent:snap-hotfix

**Expected behavior**

report error and finish restore .
