### ISSUE TITLE
backup not support `concurrency` value

### ISSUE THREAD

**Issue by jinyingsunny** [vesoft-inc/nebula-operator#456]
**Please check the FAQ documentation before raising an issue**
on AWS when do backup with sf300（3replica-24part，61亿点+变，单副本大小270G），backup cost nearly 75min.  The most time-consuming is the storage data upload, since backup default 5 concurrency，so i try to increase it, however, it report error.

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/e5dff1e7-3418-4b02-8483-20986f5e5ef3)
![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/d75e1e67-f2ce-475c-9ee5-cabfd2291706)

![image](https://github.com/vesoft-inc/nebula-operator/assets/106510322/78481697-e543-4cac-aa1b-abb63b859228)

with backup file:
```
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaBackup
metadata:
  name: nb202402282f300-2
  namespace: harris
spec:
  concurrency: "12"
  image: 527027779790.dkr.ecr.us-east-2.amazonaws.com/cloud-dev/br-ent
  version: v3.7.0
  resources:
    limits:
      cpu: "200m"
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi
  autoRemoveFinished: false
  cleanBackupData: false
  config:
    #concurrency: "12"
    clusterName: nebula
    s3:
      region: "us-west-2"
      bucket: "nebula-br-test2"
      endpoint: "https://s3.us-west-2.amazonaws.com"
      secretName: "aws-secret-ql3"
```

**Your Environments (__required__)**

operator：reg.vesoft-inc.com/cloud-dev/nebula-operator:snap-1.37
br-ent: reg.vesoft-inc.com/cloud-dev/br-ent:v3.7.0
agent: reg.vesoft-inc.com/cloud-dev/nebula-agent:snap
nebula: reg.vesoft-inc.com/qa/nebula-graphd-ent:snap-hotfix

**Expected behavior**

can accept the param `concurrency`

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/457

**Comment by jinyingsunny** [comment]
snap:1.39, has supported
`concurrency` can be set under config, eg: 
```
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaBackup
metadata:
  name: nb20240229f100-2
  namespace: harris
spec:
  image: 527027779790.dkr.ecr.us-east-2.amazonaws.com/cloud-dev/br-ent
  version: v3.7.0
  resources:
    limits:
      cpu: "200m"
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi
  autoRemoveFinished: false
  cleanBackupData: false
  config:
    concurrency: 12
    clusterName: nebulasf100
    s3:
      region: "us-west-2"
      bucket: "nebula-br-test2"
      endpoint: "https://s3.us-west-2.amazonaws.com"
      secretName: "aws-secret-ql3"
```
