### ISSUE TITLE
Introducing `nebulaschema`

### ISSUE THREAD

**Issue by haoxins** [vesoft-inc/nebula-operator#459]
Hi,
I submitted a discussion about the schema management of Nebula last year.
See https://github.com/vesoft-inc/nebula/discussions/5794.

From now on, some progressions and changes are happening.

I already introduced `ApplyEdge` & `ApplyTag` in the Nebula Go client. See https://github.com/vesoft-inc/nebula-go/pull/317 and https://github.com/vesoft-inc/nebula-go/pull/319.

So I want to move to the next step by introducing a new CRD called `nebulaschema` or `nebulamigration`? (I'm not sure what is the ideal name.)

The draft will look like

```yaml
apiVersion: apps.nebula-graph.io/v1alpha1
kind: NebulaSchema
metadata:
  name: test_01
spec:
  localNebula: false
  remoteConfig:
  # The config for the Nebula that deploys out of the same K8s cluster
    spaceName: test_space
    clusterHost: the_host
    clusterPort: 8888
    user: the_user_name
    pass: the_password
  localConfig:
  # The config for the Nebula that deploys in the same K8s cluster
  tags:
    - name: user
      fields:
      - name: name
        type: string
      - name: age
        type: int
  edges:
    - name: friend
      fields:
      - created_at
        type: timestamp
```

I opened this issue is make sure whether this idea is accepted or not for the operator.
If so, we can talk about the more details of the CRD and implementations.
