### ISSUE TITLE
Support HPA on memory resources

### ISSUE THREAD

**Issue by wenhaocs** [vesoft-inc/nebula-operator#471]

**Comment by MegaByte875** [comment]
```yaml
apiVersion: autoscaling.nebula-graph.io/v1alpha1
kind: NebulaAutoscaler
metadata:
  name: nebula-autoscaler
spec:
  nebulaClusterRef:
    name: nebula
  graphdPolicy:
    minReplicas: 2
    maxReplicas: 10
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 80
    - type: Object
      object:
        metric:
          name: nebula_graphd_num_queries_per_second
        describedObject:
          apiVersion: v1
          kind: Service
          name: nebula-exporter-svc
        target:
          type: Value
          value: 3k
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Percent
          value: 100
          periodSeconds: 15
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
        - type: Percent
          value: 200
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
        selectPolicy: Max
  pollingPeriod: 30s


```
